Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 240, in <lambda>
    command=lambda: run_tkinter_RFCcheck())
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 177, in run_tkinter_RFCcheck
    canvas.create_image(RFCcheck_window,0, 0, image=photo, anchor=NW)
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 2790, in create_image
    return self._create('image', args, kw)
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 2776, in _create
    return self.tk.getint(self.tk.call(
_tkinter.TclError: bad screen distance ".!toplevel"
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 277, in <module>
    run_tkinter_root()
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 251, in run_tkinter_root
    root.mainloop()
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
