随机森林训练模块
C:\Users\Lenovo\Desktop\python3Project\school\works\scout\traindata
C:\Users\Lenovo\Desktop\python3Project\school\works\scout\traindata\rfc-default.pkl
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 194, in <lambda>
    begintrain_button=Button(canvas,text="开始训练",font=('华文行楷', 20, 'bold'),command=lambda:trainmodel.run_trainModel(predict_result_listbox))
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\trainModel.py", line 54, in run_trainModel
    self.fileread(self.fileread_name)
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\trainModel.py", line 214, in fileread
    filelist[filename] = filepath
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 325, in <module>
    run_tkinter_root()
  File "C:\Users\Lenovo\Desktop\python3Project\school\works\scout\main.py", line 302, in run_tkinter_root
    root.mainloop()
  File "D:\Python3.9.2\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
